settings:
  service:
    # supports two kind of service modes, PTERODACTYL & Locally
    mode: PTERODACTYL

    # everything below is required to be filled in for PTERODACTYL services
    panel_url: https://pterodactyl.io/
    api_key: PUT_API_KEY_HERE
    server_id: PUT_SERVER_ID_HERE